// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package usersRepo

import (
	"context"

	"uuid"
)

const createUserQuery = `-- name: CreateUserQuery :one
INSERT INTO users (name, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateUserQueryParams struct {
	Name         string
	Email        string
	PasswordHash []byte
}

func (q *Queries) CreateUserQuery(ctx context.Context, arg CreateUserQueryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUserQuery, arg.Name, arg.Email, arg.PasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteUserQuery = `-- name: DeleteUserQuery :exec
DELETE
FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserQuery(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserQuery, id)
	return err
}

const getUserByEmailQuery = `-- name: GetUserByEmailQuery :one
SELECT id, name, email, password_hash, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmailQuery(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailQuery, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIDQuery = `-- name: GetUserByIDQuery :one
SELECT id, name, email, password_hash, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByIDQuery(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDQuery, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserQuery = `-- name: UpdateUserQuery :exec
UPDATE users
SET
    name = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateUserQueryParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateUserQuery(ctx context.Context, arg UpdateUserQueryParams) error {
	_, err := q.db.Exec(ctx, updateUserQuery, arg.ID, arg.Name)
	return err
}
