// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package organizationsRepo

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

const createMemberOwnerQuery = `-- name: CreateMemberOwnerQuery :exec
INSERT INTO members (user_id, organization_id, role)
VALUES ($1, $2, $3)
`

type CreateMemberOwnerQueryParams struct {
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
	Role           Rolestatus
}

func (q *Queries) CreateMemberOwnerQuery(ctx context.Context, arg CreateMemberOwnerQueryParams) error {
	_, err := q.db.Exec(ctx, createMemberOwnerQuery, arg.UserID, arg.OrganizationID, arg.Role)
	return err
}

const getMemberByIDQuery = `-- name: GetMemberByIDQuery :one
SELECT m.id as memberID, m.role, u.id, u.name, u.email, m.created_at, m.updated_at
FROM members m
LEFT JOIN public.users u ON m.user_id = u.id
WHERE m.id = $1 AND m.organization_id = $1
`

type GetMemberByIDQueryRow struct {
	Memberid  uuid.UUID
	Role      Rolestatus
	ID        pgtype.UUID
	Name      pgtype.Text
	Email     pgtype.Text
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetMemberByIDQuery(ctx context.Context, id uuid.UUID) (GetMemberByIDQueryRow, error) {
	row := q.db.QueryRow(ctx, getMemberByIDQuery, id)
	var i GetMemberByIDQueryRow
	err := row.Scan(
		&i.Memberid,
		&i.Role,
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembersQuery = `-- name: ListMembersQuery :many
SELECT m.id as memberId, m.role, u.id, u.name, u.email, m.created_at, m.updated_at FROM members m
LEFT JOIN public.users u ON m.user_id = u.id
WHERE m.organization_id = $1
`

type ListMembersQueryRow struct {
	Memberid  uuid.UUID
	Role      Rolestatus
	ID        pgtype.UUID
	Name      pgtype.Text
	Email     pgtype.Text
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListMembersQuery(ctx context.Context, organizationID pgtype.UUID) ([]ListMembersQueryRow, error) {
	rows, err := q.db.Query(ctx, listMembersQuery, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersQueryRow
	for rows.Next() {
		var i ListMembersQueryRow
		if err := rows.Scan(
			&i.Memberid,
			&i.Role,
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMemberQuery = `-- name: RemoveMemberQuery :exec
DELETE FROM members
WHERE id = $1
`

func (q *Queries) RemoveMemberQuery(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeMemberQuery, id)
	return err
}
