// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package organizationsRepo

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

type Planstatus string

const (
	PlanstatusPRO  Planstatus = "PRO"
	PlanstatusFREE Planstatus = "FREE"
)

func (e *Planstatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Planstatus(s)
	case string:
		*e = Planstatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Planstatus: %T", src)
	}
	return nil
}

type NullPlanstatus struct {
	Planstatus Planstatus
	Valid      bool // Valid is true if Planstatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlanstatus) Scan(value interface{}) error {
	if value == nil {
		ns.Planstatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Planstatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlanstatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Planstatus), nil
}

type Rolestatus string

const (
	RolestatusOWNER  Rolestatus = "OWNER"
	RolestatusMEMBER Rolestatus = "MEMBER"
)

func (e *Rolestatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Rolestatus(s)
	case string:
		*e = Rolestatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Rolestatus: %T", src)
	}
	return nil
}

type NullRolestatus struct {
	Rolestatus Rolestatus
	Valid      bool // Valid is true if Rolestatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRolestatus) Scan(value interface{}) error {
	if value == nil {
		ns.Rolestatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Rolestatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRolestatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Rolestatus), nil
}

type Member struct {
	ID             uuid.UUID
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
	Role           Rolestatus
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Domain    string
	Slug      string
	Plan      Planstatus
	OwnerID   pgtype.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
