// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package organizationsRepo

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

const createOrganizationQuery = `-- name: CreateOrganizationQuery :one
INSERT INTO organizations (name, domain, slug, plan, owner_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateOrganizationQueryParams struct {
	Name    string
	Domain  string
	Slug    string
	Plan    Planstatus
	OwnerID pgtype.UUID
}

func (q *Queries) CreateOrganizationQuery(ctx context.Context, arg CreateOrganizationQueryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createOrganizationQuery,
		arg.Name,
		arg.Domain,
		arg.Slug,
		arg.Plan,
		arg.OwnerID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteOrganizationQuery = `-- name: DeleteOrganizationQuery :exec
DELETE
FROM organizations
WHERE id = $1
`

func (q *Queries) DeleteOrganizationQuery(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationQuery, id)
	return err
}

const getDefaultOrganizationQuery = `-- name: GetDefaultOrganizationQuery :one
SELECT
    o.id,
    o.name,
    o.slug,
    o.domain,
    o.plan,
    o.created_at,
    o.updated_at
FROM organizations o
WHERE o.owner_id = $1
   OR EXISTS (
    SELECT 1
    FROM public.members m
    WHERE m.organization_id = o.id
      AND m.user_id = $1
)
ORDER BY o.created_at ASC, o.id ASC
LIMIT 1
`

type GetDefaultOrganizationQueryRow struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	Domain    string
	Plan      Planstatus
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetDefaultOrganizationQuery(ctx context.Context, ownerID pgtype.UUID) (GetDefaultOrganizationQueryRow, error) {
	row := q.db.QueryRow(ctx, getDefaultOrganizationQuery, ownerID)
	var i GetDefaultOrganizationQueryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationQuery = `-- name: GetOrganizationQuery :one
SELECT id, name, slug, domain, plan, created_at, updated_at
FROM organizations
WHERE id = $1
`

type GetOrganizationQueryRow struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	Domain    string
	Plan      Planstatus
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetOrganizationQuery(ctx context.Context, id uuid.UUID) (GetOrganizationQueryRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationQuery, id)
	var i GetOrganizationQueryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationQuery = `-- name: UpdateOrganizationQuery :exec
UPDATE organizations
SET
    name = $2,
    domain = $3,
    slug = $4,
    updated_at = now()
WHERE id = $1
`

type UpdateOrganizationQueryParams struct {
	ID     uuid.UUID
	Name   string
	Domain string
	Slug   string
}

func (q *Queries) UpdateOrganizationQuery(ctx context.Context, arg UpdateOrganizationQueryParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationQuery,
		arg.ID,
		arg.Name,
		arg.Domain,
		arg.Slug,
	)
	return err
}
