// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: machines.sql

package machinesRepo

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

const consumeMachineTokenQuery = `-- name: ConsumeMachineTokenQuery :one
UPDATE machine_enrollment_tokens
SET
    used_at = now(),
    updated_at = now()
WHERE token_hash = $1
  AND machine_id = $2
  AND used_at IS NULL
  AND expires_at > now()
RETURNING
    id,
    machine_id,
    token_hash,
    expires_at
`

type ConsumeMachineTokenQueryParams struct {
	TokenHash string
	MachineID uuid.UUID
}

type ConsumeMachineTokenQueryRow struct {
	ID        uuid.UUID
	MachineID uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) ConsumeMachineTokenQuery(ctx context.Context, arg ConsumeMachineTokenQueryParams) (ConsumeMachineTokenQueryRow, error) {
	row := q.db.QueryRow(ctx, consumeMachineTokenQuery, arg.TokenHash, arg.MachineID)
	var i ConsumeMachineTokenQueryRow
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.TokenHash,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteMachineQuery = `-- name: DeleteMachineQuery :exec
DELETE
FROM machines
WHERE id = $1
`

func (q *Queries) DeleteMachineQuery(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMachineQuery, id)
	return err
}

const getMachineQuery = `-- name: GetMachineQuery :one
SELECT
    id,
    organization_id,
    name,
    hostname,
    agent_version,
    last_seen_at,
    created_at,
    updated_at
FROM machines
WHERE id = $1
`

func (q *Queries) GetMachineQuery(ctx context.Context, id uuid.UUID) (Machine, error) {
	row := q.db.QueryRow(ctx, getMachineQuery, id)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Hostname,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMachineQuery = `-- name: ListMachineQuery :many
SELECT
    id,
    organization_id,
    name,
    hostname,
    agent_version,
    last_seen_at,
    created_at,
    updated_at
FROM machines
WHERE organization_id = $1
ORDER BY created_at
`

func (q *Queries) ListMachineQuery(ctx context.Context, organizationID uuid.UUID) ([]Machine, error) {
	rows, err := q.db.Query(ctx, listMachineQuery, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Machine
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Hostname,
			&i.AgentVersion,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerMachineQuery = `-- name: RegisterMachineQuery :one
INSERT INTO machines (organization_id, name)
VALUES ($1, $2)
RETURNING id
`

type RegisterMachineQueryParams struct {
	OrganizationID uuid.UUID
	Name           string
}

func (q *Queries) RegisterMachineQuery(ctx context.Context, arg RegisterMachineQueryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, registerMachineQuery, arg.OrganizationID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const registerTokenMachineQuery = `-- name: RegisterTokenMachineQuery :exec
INSERT INTO machine_enrollment_tokens (machine_id, token_hash, expires_at, created_by_user_id)
VALUES ($1, $2, $3, $4)
`

type RegisterTokenMachineQueryParams struct {
	MachineID       uuid.UUID
	TokenHash       string
	ExpiresAt       time.Time
	CreatedByUserID uuid.UUID
}

func (q *Queries) RegisterTokenMachineQuery(ctx context.Context, arg RegisterTokenMachineQueryParams) error {
	_, err := q.db.Exec(ctx, registerTokenMachineQuery,
		arg.MachineID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedByUserID,
	)
	return err
}

const updateMachineNameQuery = `-- name: UpdateMachineNameQuery :exec
UPDATE machines
SET name = $2, updated_at = now()
WHERE id = $1
`

type UpdateMachineNameQueryParams struct {
	ID   uuid.UUID
	Name string
}

// name is changed separately from agent heartbeat updates.
func (q *Queries) UpdateMachineNameQuery(ctx context.Context, arg UpdateMachineNameQueryParams) error {
	_, err := q.db.Exec(ctx, updateMachineNameQuery, arg.ID, arg.Name)
	return err
}

const updateMachineQuery = `-- name: UpdateMachineQuery :exec
UPDATE machines
SET
    hostname = $2,
    agent_version = $3,
    last_seen_at = $4,
    updated_at = now()
WHERE id = $1
`

type UpdateMachineQueryParams struct {
	ID           uuid.UUID
	Hostname     pgtype.Text
	AgentVersion pgtype.Text
	LastSeenAt   pgtype.Timestamptz
}

func (q *Queries) UpdateMachineQuery(ctx context.Context, arg UpdateMachineQueryParams) error {
	_, err := q.db.Exec(ctx, updateMachineQuery,
		arg.ID,
		arg.Hostname,
		arg.AgentVersion,
		arg.LastSeenAt,
	)
	return err
}
