// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package machinesRepo

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

type Planstatus string

const (
	PlanstatusPRO  Planstatus = "PRO"
	PlanstatusFREE Planstatus = "FREE"
)

func (e *Planstatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Planstatus(s)
	case string:
		*e = Planstatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Planstatus: %T", src)
	}
	return nil
}

type NullPlanstatus struct {
	Planstatus Planstatus
	Valid      bool // Valid is true if Planstatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlanstatus) Scan(value interface{}) error {
	if value == nil {
		ns.Planstatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Planstatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlanstatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Planstatus), nil
}

type Machine struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Hostname       pgtype.Text
	AgentVersion   pgtype.Text
	LastSeenAt     pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type MachineEnrollmentToken struct {
	ID              uuid.UUID
	MachineID       uuid.UUID
	TokenHash       string
	UsedAt          pgtype.Timestamptz
	ExpiresAt       time.Time
	CreatedByUserID uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Domain    string
	Slug      string
	Plan      Planstatus
	OwnerID   pgtype.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}
